version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - opensearch-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:5601/status | grep -q '\"status\":\"green\"'"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      opensearch:
        condition: service_healthy

  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ${HOME}/.ollama:/root/.ollama
    environment:
      - DOWNLOAD_MODELS=false
      - MODELS=mxbai-embed-large,phi3.5
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4'
        reservations:
          memory: 4G
          cpus: '2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - opensearch-network
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864

  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - DEBIAN_FRONTEND=noninteractive
        - PIP_NO_CACHE_DIR=1
    container_name: app
    ports:
      - "8081:8081"
    environment:
      - ENV_FILE=/app/secrets/.env
      - GRADIO_ALLOWED_ORIGINS=["*"]
      # Service connections
      - OLLAMA_HOST=http://host.docker.internal:11434
      - EMBEDDINGS_MODEL=mxbai-embed-large
      - LLM_MODEL=phi3.5
      - EMBEDDER_TYPE=ollama
      - LLM_TYPE=ollama
      - OPENSEARCH_URL=http://opensearch:9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=admin
      - OPENSEARCH_INDEX_NAME=documents
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Processing settings
      - EMBEDDING_PROVIDER=ollama
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=200
      # Debug settings
      - PYTHONUNBUFFERED=1
    volumes:
      - ../src:/app/src
      - ./logs:/app/logs
      - ./secrets:/app/secrets
    secrets:
      - app_env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      opensearch-network:
        aliases:
          - app
    depends_on:
      opensearch:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      opensearch-network:
        aliases:
          - redis
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  opensearch-data:
    driver: local

networks:
  opensearch-network:
    driver: bridge

secrets:
  app_env:
    file: .env
